# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
    
jobs:
  build:
    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Build
      run: |
        go mod download
        go build -v ./...
    
    - name: Publish build
      uses: actions/upload-artifact@v3
      with:
        name: github-pages
        path: ${{ github.workspace }}

    - name: Run
      id: deployment
      uses: actions/deploy-pages@v1
