# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "login_feature" ]
  pull_request:
    branches: [ "login_feature" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Build
      run: |
        go mod download
        go build -v ./...
    
    - name: Publish build
      uses: actions/upload-artifact@v3
      with:
        name: AwesomeAPIexercise
        path: ${{ github.workspace }}

    - name: Run
      uses: actions/deploy-pages@v1
